using CMSv2026WebApp.Models;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;


namespace CMSv2026WebApp.Service
{
    public class PdfService
    {
        public byte[] GenerateLabTestReportPdf(LabTestReport labTestReport)
        {
            using (var stream = new MemoryStream())
            {
                // Initialize PDF writer
                var writer = new PdfWriter(stream);
                var pdf = new PdfDocument(writer);

                // Create the document
                var document = new Document(pdf);

                // Add content to the PDF
                document.Add(new Paragraph("Lab Test Report")
                    .SetTextAlignment(TextAlignment.CENTER)
                    .SetFontSize(20));

                document.Add(new Paragraph($"Test Name: {labTestReport.TestName}"));
                document.Add(new Paragraph($"Patient Name: {labTestReport.PatientName}"));
                document.Add(new Paragraph($"Prescribed By Doctor: {labTestReport.PrescribedByDoctor}"));
                document.Add(new Paragraph($"Generated By Lab Technician: {labTestReport.GeneratedByLabTechnician}"));
                document.Add(new Paragraph($"Report Date: {labTestReport.ReportDate}"));
                document.Add(new Paragraph($"Remarks: {labTestReport.Remarks}"));

                // Close the document
                document.Close();

                // Return the PDF as a byte array
                return stream.ToArray();
            }
        }
    }
}